#define DYNEventSpecial
/* DSblock model generated by Dymola from Modelica model SMIBPS_IdControl.Analysis.LinearAnalysis.Linearization.LinearModelExample
 Dymola Version 2020x (64-bit), 2019-10-10 translated this at Fri Oct 30 13:50:40 2020

  Evaluate = true;
OutputCPUtime = true;
 */

#include <matrixop.h>
#if defined(DynSimStruct) || defined(BUILDFMU)
static double DymArrays5[3]={1.0, 1.0, 0.0};
static double DymArrays0[3]={1.0, 1.0, 1.0};
static double DymArrays2[3]={3.0, 1.0, 2.0};
static double DymArrays1[5]={1.0, 1.0, 1.0, 1.0, 1.0};
static double DymArrays6[6]={1.2242474555969238, 1.0, 0.4360022246837616, 
  0.8999999761581421, 1.0, 1.2242474555969238};
static double DymArrays4[11]={0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 
  0.0};
static double DymArrays3[99]={0.0, 376.99111838914104, 0.0, 0.0, 0.0, 0.0, 
  -0.15935012502522555, 0.0, 0.0, 0.0, -0.1730203086974122, 0.06000759113665713,
   -0.225786591276862, 0.0, -0.12499999999582975, 0.0, -0.2668898899908987, 
  -0.0011041056183099536, 0.46107962381245693, 0.0, 0.0, -1.0000000000758573, 
  0.006336424569356028, -1.4894289460374501, -2.9728307608838804, 0.0, 
  33.33333333222127, 0.0, -36.84735279230479, -0.014537265192078836, 
  2.6215590291419555, 0.0, 0.0, 14.285714286797962, 0.0360269902464371, 
  -22.754155959037135, 0.0, 0.0, 0.0, 0.0, 0.14285715467720342, -0.031538676432360496,
   0.12500001034254637, 0.0, -0.04074007797782997, 0.0, 0.0, 0.09771200515373835,
   0.0, 0.0, -0.5364063360158156, 0.0, 0.0, 0.5555611526375515, -0.13790065289076472,
   0.0, 0.0, 0.0, 0.4364388135635919, 0.4994401309217214, 0.3122089845885527, 
  0.0, 0.0, 0.0, 1.4657741561523794, 0.7706076485898833, 1.2147747709609267, 0.0,
   0.0, 0.0, 1.371465981949742, -0.3580020102583231, 0.0, 0.999999999889562, 0.0,
   0.0, 0.0, 0.0, 0.9999999998632589, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 
  -0.015863310665054087, 0.0, 0.0, 0.02177458213736827, 0.0, 0.0, 
  0.21947843542591272, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0};
#endif
/* Declaration of C-structs */
/* Prototypes for functions used in model */
/* Codes used in model */
/* DSblock C-code: */

#define NX_    6
#define NX2_   0
#define NU_    0
#define NY_    7
#define NW_    192
#define NP_    0
#define NPS_   0
#define ND_   0
#define NXP_   0
#define NInitial_   0
#define MAXAuxStr_   14
#define MAXAuxStrLen_   500
#define NHash1_ 154075073
#define NHash2_ -701576645
#define NHash3_ 0
#define NI_    0
#define NRelF_ 0
#define NRel_  0
#define NTim_  1
#define NSamp_ 0
#define NCons_ 0
#define NA_    23
#define SizePre_ 0
#define SizeEq_ 0
#define SizeDelay_ 0
#define QNLmax_ 0
#define MAXAux 0
#define NrDymolaTimers_ 0
#define NWhen_ 0
#define NCheckIf_ 0
#define NGlobalHelp_ 0
#define NGlobalHelpI_ 0
#ifndef NExternalObject_
#define NExternalObject_ 0
#endif
#include <moutil.c>
DYMOLA_STATIC unsigned int FMIClockValueReferences_[1]={0};
DYMOLA_STATIC unsigned int FMIClockFirstValueReferences_[1]={0};
PreNonAliasDef(0)
PreNonAliasDef(1)
PreNonAliasDef(2)
PreNonAliasDef(3)
PreNonAliasDef(4)
PreNonAliasDef(5)
#if !defined(DYM2CCUR)
 DYMOLA_STATIC const char*modelName="SMIBPS_IdControl.Analysis.LinearAnalysis.Linearization.LinearModelExample";
#endif
DYMOLA_STATIC const char*usedLibraries[]={0};
DYMOLA_STATIC const char*dllLibraryPath[]={0};
DYMOLA_STATIC const char*default_dymosim_license_filename=
 "c:/users/meagh/appdata/roaming/dassaultsystemes/dymola/dymola.lic";
#define QJacobianCGDef_ 1
DYMOLA_STATIC int QJacobianCG_[13]={4 , 2 , 1 , 2 , 2 , 3 , 4 , 1 , 5 , 1 , 6 , 0
   , 0};
static int QJacobianGrp0[7]={2, 1, 1, 1, 1, 1, 0};
static int QJacobianGrp1[7]={0, 0, 3, 4, 3, 4, 0};
static int QJacobianGrp2[7]={0, 5, 5, 5, 5, 5, 0};
static int QJacobianGrp3[7]={0, 6, 6, 6, 6, 6, 0};
DYMOLA_STATIC struct QJacobianTag_ QJacobianGC2_[5]={
{0, QJacobianGrp0},{0, QJacobianGrp1},{0, QJacobianGrp2},{0, QJacobianGrp3},
  {0,0}};
DYMOLA_STATIC double QJacobianCD_[7]={0  , 44 , 55 , 60 , 70 , 72 , 72};
#include <dsblock1.c>

/* Define variable names. */

#define Sections_

TranslatedEquations
DYNX(Y_,5) = CurrentClockTime;
if (DYNEvent) DYNX(Y_,6) += 1;

InitialSection
#if defined(DynSimStruct) || defined(BUILDFMU)
DYNX(W_,0) = 1;
memcpy(&DYNX(W_,9), &DymArrays0, sizeof(double)*3);
DYNX(W_,116) = 1;
DYNX(W_,117) = true;
DYNX(W_,140) = 6;
DYNX(W_,141) = 5;
memcpy(&DYNX(W_,143), &DymArrays1, sizeof(double)*5);
memcpy(&DYNX(W_,165), &DymArrays1, sizeof(double)*5);
memcpy(&DYNX(W_,1), &DymArrays2, sizeof(double)*3);
DYNX(W_,5) = 0.01;
DYNX(W_,7) = 0;
DYNX(W_,8) = 1;
memcpy(&DYNX(W_,16), &DymArrays3, sizeof(double)*99);
#endif
DYNSetAuxString(did_, "Vt", 0);
DYNSetAuxString(did_, "Q", 1);
DYNSetAuxString(did_, "P", 2);
DYNSetAuxString(did_, "w", 3);
DYNSetAuxString(did_, "delta", 4);
DYNSetAuxString(did_, "G1.machine.delta", 5);
DYNSetAuxString(did_, "G1.machine.w", 6);
DYNSetAuxString(did_, "G1.machine.e1q", 7);
DYNSetAuxString(did_, "G1.machine.e1d", 8);
DYNSetAuxString(did_, "G1.machine.e2q", 9);
DYNSetAuxString(did_, "G1.machine.e2d", 10);
DYNSetAuxString(did_, "uEfd", 11);
DYNSetAuxString(did_, "uPm", 12);
DYNSetAuxString(did_, "uPload", 13);
#if defined(DynSimStruct) || defined(BUILDFMU)
DYNX(W_,118) = 7;
DYNX(W_,121) = 5;
DYNX(W_,119) = 2;
DYNX(W_,120) = 1;
memcpy(&DYNX(W_,122), &DymArrays4, sizeof(double)*11);
DYNX(W_,142) = false;
DYNX(W_,149) = 1;
DYNX(W_,150) = 1;
DYNX(W_,152) = 1;
DYNX(W_,153) = 1;
DYNX(W_,155) = 1;
DYNX(W_,156) = 1;
DYNX(W_,158) = 1;
DYNX(W_,159) = 1;
memcpy(&DYNX(W_,161), &DymArrays5, sizeof(double)*3);
DYNX(W_,180) = 1;
DYNX(W_,182) = 0.4360022246837616;
DYNX(W_,184) = 0.8999999761581421;
DYNX(W_,186) = 1;
DYNX(W_,188) = 1.2242474555969238;
DYNX(W_,190) = 0;
DYNX(W_,13) = 0.0;
DYNX(W_,12) = 0.0;
DYNX(W_,170) = 1.0;
DYNX(W_,173) = 1.0;
DYNX(W_,191) = 0.0;
DYNX(W_,164) = 0.0;
DYNX(W_,148) = 1.0;
DYNX(W_,151) = 0.4360022246837616;
DYNX(W_,154) = 0.8999999761581421;
DYNX(W_,157) = 1.0;
DYNX(W_,160) = 1.2242474555969238;
DYNX(W_,14) = 0.0;
DYNX(W_,15) = 0.0;
DYNX(W_,171) = 0.4360022246837616;
DYNX(W_,172) = 0.8999999761581421;
memcpy(&DYNX(W_,174), &DymArrays6, sizeof(double)*6);
DYNX(W_,4) = false;
DYNX(W_,115) = true;
DYNX(W_,133) = 0.0;
DYNX(W_,134) = 0.0;
DYNX(W_,185) = 0.8999999761581421;
DYNX(W_,183) = 0.4360022246837616;
DYNX(W_,181) = 1.0;
DYNX(W_,189) = 1.2242474555969238;
DYNX(W_,187) = 1.0;
#endif
if (!DymolaUserHomotopy) UpdateInitVars(time, X_, XD_, U_, DP_, IP_, LP_, F_, Y_, W_, QZ_, duser_, iuser_, cuser_, did_, 1);
BoundParameterSection
InitialSection
InitialSection
InitialStartSection
InitialSection
if (!DymolaUserHomotopy) UpdateInitVars(time, X_, XD_, U_, DP_, IP_, LP_, F_, Y_, W_, QZ_, duser_, iuser_, cuser_, did_, 1);
DefaultSection
InitializeData(0)
InitialSection
InitialSection2
DYNX(W_,138) = 0.0;
DYNX(Y_,3) = 1.0;
DYNX(F_,5) = 0.0;
DYNX(F_,2) = 0.0;
DYNX(F_,4) = 0.0;
DYNX(F_,1) = 0.0;
DYNX(F_,0) = 0.0;
DYNX(F_,3) = 0.0;
DYNX(X_,1) = 0.0;
DYNX(W_,6) = IF LessTime(1, 0) THEN 0 ELSE 0.01;

DYNX(X_,4) = 0.9935546774323403*DYNX(W_,6);
DYNX(X_,5) = (-0.24179544079822413)*DYNX(W_,6);
DYNX(X_,0) = 6.27548927144988*(0.06000759113665713*DYNX(X_,5)-0.1730203086974122
  *DYNX(X_,4));
DYNX(X_,3) = 0.9999999999241427*(0.46107962381245693*DYNX(X_,0)+0.006336424569356028
  *DYNX(X_,4)-1.4894289460374501*DYNX(X_,5));
DYNX(X_,2) = 8.000000000266896*((-0.225786591276862)*DYNX(X_,0)-0.2668898899908987
  *DYNX(X_,4)-0.0011041056183099536*DYNX(X_,5)+0.12500001034254637*DYNX(W_,6));

InitialSection
InitialSectionB
Init_=false;InitializeData(2);Init_=true;
EndInitialSection

OutputSection
DYNX(W_,135) = 0.4364388135635919*DYNX(X_,4)-0.13790065289076472*DYNX(X_,0)+
  0.4994401309217214*DYNX(X_,5);
DYNX(Y_,0) = 1.0+DYNX(W_,135);
DYNX(W_,136) = 0.3122089845885527*DYNX(X_,0)+1.4657741561523794*DYNX(X_,4)+
  0.7706076485898833*DYNX(X_,5);
DYNX(Y_,1) = 0.4360022246837616+DYNX(W_,136);
DYNX(W_,137) = 1.2147747709609267*DYNX(X_,0)+1.371465981949742*DYNX(X_,4)-
  0.3580020102583231*DYNX(X_,5);
DYNX(Y_,2) = 0.8999999761581421+DYNX(W_,137);
DYNX(W_,138) = 0.999999999889562*DYNX(X_,1);
DYNX(Y_,3) = 1.0+DYNX(W_,138);
DYNX(W_,139) = 0.9999999998632589*DYNX(X_,0);
DYNX(Y_,4) = 1.2242474555969238+DYNX(W_,139);

DynamicsSection
DYNX(F_,5) = 2.6215590291419555*DYNX(X_,0)+14.285714286797962*DYNX(X_,3)+
  0.0360269902464371*DYNX(X_,4)-22.754155959037135*DYNX(X_,5);
DYNX(W_,6) = IF LessTime(1, 0) THEN 0 ELSE 0.01;
DYNX(F_,2) = (-0.225786591276862)*DYNX(X_,0)-0.12499999999582975*DYNX(X_,2)-
  0.2668898899908987*DYNX(X_,4)-0.0011041056183099536*DYNX(X_,5)+
  0.12500001034254637*DYNX(W_,6);
DYNX(F_,4) = 33.33333333222127*DYNX(X_,2)-2.9728307608838804*DYNX(X_,0)-
  36.84735279230479*DYNX(X_,4)-0.014537265192078836*DYNX(X_,5);
DYNX(F_,1) = (-0.15935012502522555)*DYNX(X_,0)-0.1730203086974122*DYNX(X_,4)+
  0.06000759113665713*DYNX(X_,5);
DYNX(F_,0) = 376.99111838914104*DYNX(X_,1);
DYNX(F_,3) = 0.46107962381245693*DYNX(X_,0)-1.0000000000758573*DYNX(X_,3)+
  0.006336424569356028*DYNX(X_,4)-1.4894289460374501*DYNX(X_,5);

AcceptedSection1

AcceptedSection2

DefaultSection
InitializeData(1)
EndTranslatedEquations

#include <dsblock6.c>

PreNonAliasNew(0)
StartNonAlias(0)
DeclareVariable("sampleClock.blockType", "Type of Sampled blocks [:#(type=Modelica_LinearSystems2.Controller.Types.BlockType)]",\
 1, 1.0,2.0,0.0,0,517)
DeclareVariable("sampleClock.methodType", "Discretization method for discrete blocks [:#(type=Modelica_LinearSystems2.Utilities.Types.Method)]",\
 3, 1.0,6.0,0.0,0,517)
DeclareVariable("sampleClock.sampleTime", "Base sample time for discrete blocks [s]",\
 1, 0.0,0.0,0.0,0,513)
DeclareVariable("sampleClock.initType", "Type of initialization of Sampled blocks [:#(type=Modelica_LinearSystems2.Controller.Types.Init)]",\
 2, 1.0,4.0,0.0,0,517)
DeclareVariable("sampleClock.sampleTrigger", "Trigger that is true at every sampleTime [:#(type=Boolean)]",\
 false, 0.0,0.0,0.0,0,1539)
DeclareOutput("Vt", "", 0, 0.0, 0.0,0.0,0.0,0,512)
DeclareOutput("Q", "", 1, 0.0, 0.0,0.0,0.0,0,512)
DeclareOutput("P", "", 2, 0.0, 0.0,0.0,0.0,0,512)
DeclareOutput("w", "", 3, 0.0, 0.0,0.0,0.0,0,512)
DeclareOutput("delta", "", 4, 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("stepEfd.height", "Height of step", 0.01, 0.0,0.0,0.0,0,513)
DeclareVariable("stepEfd.y", "Connector of Real output signal", 0.0, 0.0,0.0,0.0,\
0,640)
DeclareVariable("stepEfd.offset", "Offset of output signal y", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("stepEfd.startTime", "Output y = offset for time < startTime [s]",\
 1, 0.0,0.0,0.0,0,513)
DeclareVariable("multiplex3_1.n1", "Dimension of input signal connector 1 [:#(type=Integer)]",\
 1, 0.0,0.0,0.0,0,517)
DeclareVariable("multiplex3_1.n2", "Dimension of input signal connector 2 [:#(type=Integer)]",\
 1, 0.0,0.0,0.0,0,517)
DeclareVariable("multiplex3_1.n3", "Dimension of input signal connector 3 [:#(type=Integer)]",\
 1, 0.0,0.0,0.0,0,517)
DeclareAlias2("multiplex3_1.u1[1]", "Connector of Real input signals 1", \
"stepEfd.y", 1, 5, 6, 0)
DeclareVariable("multiplex3_1.u2[1]", "Connector of Real input signals 2", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("multiplex3_1.u3[1]", "Connector of Real input signals 3", 0.0, \
0.0,0.0,0.0,0,513)
DeclareAlias2("multiplex3_1.y[1]", "Connector of Real output signals", \
"stepEfd.y", 1, 5, 6, 0)
DeclareVariable("multiplex3_1.y[2]", "Connector of Real output signals", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("multiplex3_1.y[3]", "Connector of Real output signals", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("stateSpace.system.A[1, 1]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("stateSpace.system.A[1, 2]", "", 376.99111838914104, 0.0,0.0,0.0,\
0,513)
DeclareVariable("stateSpace.system.A[1, 3]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("stateSpace.system.A[1, 4]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("stateSpace.system.A[1, 5]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("stateSpace.system.A[1, 6]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("stateSpace.system.A[2, 1]", "", -0.15935012502522555, 0.0,0.0,\
0.0,0,513)
DeclareVariable("stateSpace.system.A[2, 2]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("stateSpace.system.A[2, 3]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("stateSpace.system.A[2, 4]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("stateSpace.system.A[2, 5]", "", -0.1730203086974122, 0.0,0.0,\
0.0,0,513)
DeclareVariable("stateSpace.system.A[2, 6]", "", 0.06000759113665713, 0.0,0.0,\
0.0,0,513)
DeclareVariable("stateSpace.system.A[3, 1]", "", -0.225786591276862, 0.0,0.0,0.0,\
0,513)
DeclareVariable("stateSpace.system.A[3, 2]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("stateSpace.system.A[3, 3]", "", -0.12499999999582975, 0.0,0.0,\
0.0,0,513)
DeclareVariable("stateSpace.system.A[3, 4]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("stateSpace.system.A[3, 5]", "", -0.2668898899908987, 0.0,0.0,\
0.0,0,513)
DeclareVariable("stateSpace.system.A[3, 6]", "", -0.0011041056183099536, \
0.0,0.0,0.0,0,513)
DeclareVariable("stateSpace.system.A[4, 1]", "", 0.46107962381245693, 0.0,0.0,\
0.0,0,513)
DeclareVariable("stateSpace.system.A[4, 2]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("stateSpace.system.A[4, 3]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("stateSpace.system.A[4, 4]", "", -1.0000000000758573, 0.0,0.0,\
0.0,0,513)
DeclareVariable("stateSpace.system.A[4, 5]", "", 0.006336424569356028, 0.0,0.0,\
0.0,0,513)
DeclareVariable("stateSpace.system.A[4, 6]", "", -1.4894289460374501, 0.0,0.0,\
0.0,0,513)
DeclareVariable("stateSpace.system.A[5, 1]", "", -2.9728307608838804, 0.0,0.0,\
0.0,0,513)
DeclareVariable("stateSpace.system.A[5, 2]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("stateSpace.system.A[5, 3]", "", 33.33333333222127, 0.0,0.0,0.0,\
0,513)
DeclareVariable("stateSpace.system.A[5, 4]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("stateSpace.system.A[5, 5]", "", -36.84735279230479, 0.0,0.0,0.0,\
0,513)
DeclareVariable("stateSpace.system.A[5, 6]", "", -0.014537265192078836, 0.0,0.0,\
0.0,0,513)
DeclareVariable("stateSpace.system.A[6, 1]", "", 2.6215590291419555, 0.0,0.0,0.0,\
0,513)
DeclareVariable("stateSpace.system.A[6, 2]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("stateSpace.system.A[6, 3]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("stateSpace.system.A[6, 4]", "", 14.285714286797962, 0.0,0.0,0.0,\
0,513)
DeclareVariable("stateSpace.system.A[6, 5]", "", 0.0360269902464371, 0.0,0.0,0.0,\
0,513)
DeclareVariable("stateSpace.system.A[6, 6]", "", -22.754155959037135, 0.0,0.0,\
0.0,0,513)
DeclareVariable("stateSpace.system.B[1, 1]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("stateSpace.system.B[1, 2]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("stateSpace.system.B[1, 3]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("stateSpace.system.B[2, 1]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("stateSpace.system.B[2, 2]", "", 0.14285715467720342, 0.0,0.0,\
0.0,0,513)
DeclareVariable("stateSpace.system.B[2, 3]", "", -0.031538676432360496, 0.0,0.0,\
0.0,0,513)
DeclareVariable("stateSpace.system.B[3, 1]", "", 0.12500001034254637, 0.0,0.0,\
0.0,0,513)
DeclareVariable("stateSpace.system.B[3, 2]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("stateSpace.system.B[3, 3]", "", -0.04074007797782997, 0.0,0.0,\
0.0,0,513)
DeclareVariable("stateSpace.system.B[4, 1]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("stateSpace.system.B[4, 2]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("stateSpace.system.B[4, 3]", "", 0.09771200515373835, 0.0,0.0,\
0.0,0,513)
DeclareVariable("stateSpace.system.B[5, 1]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("stateSpace.system.B[5, 2]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("stateSpace.system.B[5, 3]", "", -0.5364063360158156, 0.0,0.0,\
0.0,0,513)
DeclareVariable("stateSpace.system.B[6, 1]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("stateSpace.system.B[6, 2]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("stateSpace.system.B[6, 3]", "", 0.5555611526375515, 0.0,0.0,0.0,\
0,513)
DeclareVariable("stateSpace.system.C[1, 1]", "", -0.13790065289076472, 0.0,0.0,\
0.0,0,513)
DeclareVariable("stateSpace.system.C[1, 2]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("stateSpace.system.C[1, 3]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("stateSpace.system.C[1, 4]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("stateSpace.system.C[1, 5]", "", 0.4364388135635919, 0.0,0.0,0.0,\
0,513)
DeclareVariable("stateSpace.system.C[1, 6]", "", 0.4994401309217214, 0.0,0.0,0.0,\
0,513)
DeclareVariable("stateSpace.system.C[2, 1]", "", 0.3122089845885527, 0.0,0.0,0.0,\
0,513)
DeclareVariable("stateSpace.system.C[2, 2]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("stateSpace.system.C[2, 3]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("stateSpace.system.C[2, 4]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("stateSpace.system.C[2, 5]", "", 1.4657741561523794, 0.0,0.0,0.0,\
0,513)
DeclareVariable("stateSpace.system.C[2, 6]", "", 0.7706076485898833, 0.0,0.0,0.0,\
0,513)
DeclareVariable("stateSpace.system.C[3, 1]", "", 1.2147747709609267, 0.0,0.0,0.0,\
0,513)
DeclareVariable("stateSpace.system.C[3, 2]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("stateSpace.system.C[3, 3]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("stateSpace.system.C[3, 4]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("stateSpace.system.C[3, 5]", "", 1.371465981949742, 0.0,0.0,0.0,\
0,513)
DeclareVariable("stateSpace.system.C[3, 6]", "", -0.3580020102583231, 0.0,0.0,\
0.0,0,513)
DeclareVariable("stateSpace.system.C[4, 1]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("stateSpace.system.C[4, 2]", "", 0.999999999889562, 0.0,0.0,0.0,\
0,513)
DeclareVariable("stateSpace.system.C[4, 3]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("stateSpace.system.C[4, 4]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("stateSpace.system.C[4, 5]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("stateSpace.system.C[4, 6]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("stateSpace.system.C[5, 1]", "", 0.9999999998632589, 0.0,0.0,0.0,\
0,513)
DeclareVariable("stateSpace.system.C[5, 2]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("stateSpace.system.C[5, 3]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("stateSpace.system.C[5, 4]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("stateSpace.system.C[5, 5]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("stateSpace.system.C[5, 6]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("stateSpace.system.D[1, 1]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("stateSpace.system.D[1, 2]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("stateSpace.system.D[1, 3]", "", -0.015863310665054087, 0.0,0.0,\
0.0,0,513)
DeclareVariable("stateSpace.system.D[2, 1]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("stateSpace.system.D[2, 2]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("stateSpace.system.D[2, 3]", "", 0.02177458213736827, 0.0,0.0,\
0.0,0,513)
DeclareVariable("stateSpace.system.D[3, 1]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("stateSpace.system.D[3, 2]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("stateSpace.system.D[3, 3]", "", 0.21947843542591272, 0.0,0.0,\
0.0,0,513)
DeclareVariable("stateSpace.system.D[4, 1]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("stateSpace.system.D[4, 2]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("stateSpace.system.D[4, 3]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("stateSpace.system.D[5, 1]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("stateSpace.system.D[5, 2]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("stateSpace.system.D[5, 3]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("stateSpace.cont", "[:#(type=Boolean)]", true, 0.0,0.0,0.0,0,2563)
DeclareVariable("stateSpace.blockType", "Type of block [:#(type=Modelica_LinearSystems2.Controller.Types.BlockTypeWithGlobalDefault)]",\
 1, 1.0,3.0,0.0,0,1541)
DeclareVariable("stateSpace.continuous", "True, if continuous block, otherwise discrete block [:#(type=Boolean)]",\
 true, 0.0,0.0,0.0,0,515)
DeclareVariable("stateSpace.methodType", "Type of discretization if discrete block [:#(type=Modelica_LinearSystems2.Controller.Types.MethodWithGlobalDefault)]",\
 7, 1.0,7.0,0.0,0,1541)
DeclareVariable("stateSpace.init", "Type of initialization (no init/steady state/initial state/initial output) [:#(type=Modelica_LinearSystems2.Controller.Types.Init)]",\
 2, 1.0,4.0,0.0,0,517)
DeclareVariable("stateSpace.sampleFactor", "Sample factor (Ts = sampleFactor * sampleClock.sampleTime) [:#(type=Integer)]",\
 1, 1.0,1E+100,0.0,0,517)
DeclareVariable("stateSpace.initType", "Type of initialization (no init/steady state/initial state/initial output) [:#(type=Modelica_LinearSystems2.Controller.Types.InitWithGlobalDefault)]",\
 5, 1.0,5.0,0.0,0,1541)
DeclareVariable("stateSpace.x_start[1]", "Initial or guess values of states", 0,\
 0.0,0.0,0.0,0,513)
DeclareVariable("stateSpace.x_start[2]", "Initial or guess values of states", 0,\
 0.0,0.0,0.0,0,513)
DeclareVariable("stateSpace.x_start[3]", "Initial or guess values of states", 0,\
 0.0,0.0,0.0,0,513)
DeclareVariable("stateSpace.x_start[4]", "Initial or guess values of states", 0,\
 0.0,0.0,0.0,0,513)
DeclareVariable("stateSpace.x_start[5]", "Initial or guess values of states", 0,\
 0.0,0.0,0.0,0,513)
DeclareVariable("stateSpace.x_start[6]", "Initial or guess values of states", 0,\
 0.0,0.0,0.0,0,513)
DeclareVariable("stateSpace.y_start[1]", "Initial values of outputs (remaining states are in steady state if possible)",\
 0, 0.0,0.0,0.0,0,513)
DeclareVariable("stateSpace.y_start[2]", "Initial values of outputs (remaining states are in steady state if possible)",\
 0, 0.0,0.0,0.0,0,513)
DeclareVariable("stateSpace.y_start[3]", "Initial values of outputs (remaining states are in steady state if possible)",\
 0, 0.0,0.0,0.0,0,513)
DeclareVariable("stateSpace.y_start[4]", "Initial values of outputs (remaining states are in steady state if possible)",\
 0, 0.0,0.0,0.0,0,513)
DeclareVariable("stateSpace.y_start[5]", "Initial values of outputs (remaining states are in steady state if possible)",\
 0, 0.0,0.0,0.0,0,513)
DeclareAlias2("stateSpace.u[1]", "Continuous or discrete input signals of block",\
 "stepEfd.y", 1, 5, 6, 0)
DeclareVariable("stateSpace.u[2]", "Continuous or discrete input signals of block",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("stateSpace.u[3]", "Continuous or discrete input signals of block",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("stateSpace.y[1]", "Continuous or discrete output signals of block",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("stateSpace.y[2]", "Continuous or discrete output signals of block",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("stateSpace.y[3]", "Continuous or discrete output signals of block",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("stateSpace.y[4]", "Continuous or discrete output signals of block",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("stateSpace.y[5]", "Continuous or discrete output signals of block",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareState("stateSpace.x[1]", "State vector of continuous system", 0, 0, \
0.0,0.0,0.0,0,544)
DeclareDerivative("stateSpace.der(x[1])", "der(State vector of continuous system)",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareState("stateSpace.x[2]", "State vector of continuous system", 1, 0, \
0.0,0.0,0.0,0,544)
DeclareDerivative("stateSpace.der(x[2])", "der(State vector of continuous system)",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareState("stateSpace.x[3]", "State vector of continuous system", 2, 0, \
0.0,0.0,0.0,0,544)
DeclareDerivative("stateSpace.der(x[3])", "der(State vector of continuous system)",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareState("stateSpace.x[4]", "State vector of continuous system", 3, 0, \
0.0,0.0,0.0,0,544)
DeclareDerivative("stateSpace.der(x[4])", "der(State vector of continuous system)",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareState("stateSpace.x[5]", "State vector of continuous system", 4, 0, \
0.0,0.0,0.0,0,544)
DeclareDerivative("stateSpace.der(x[5])", "der(State vector of continuous system)",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareState("stateSpace.x[6]", "State vector of continuous system", 5, 0, \
0.0,0.0,0.0,0,544)
DeclareDerivative("stateSpace.der(x[6])", "der(State vector of continuous system)",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("stateSpace.nx", "Number of states x [:#(type=Integer)]", 6, \
0.0,0.0,0.0,0,1541)
DeclareVariable("stateSpace.ny", "Number of outputs y [:#(type=Integer)]", 5, \
0.0,0.0,0.0,0,1541)
DeclareVariable("stateSpace.withDelay", "True, if a unit delay should be considered [:#(type=Boolean)]",\
 false, 0.0,0.0,0.0,0,1539)
DeclareVariable("demultiplex2_2.n1", "Dimension of output signal connector 1 [:#(type=Integer)]",\
 1, 0.0,0.0,0.0,0,517)
DeclareVariable("demultiplex2_2.n2", "Dimension of output signal connector 2 [:#(type=Integer)]",\
 1, 0.0,0.0,0.0,0,517)
DeclareVariable("demultiplex2_2.n3", "Dimension of output signal connector 3 [:#(type=Integer)]",\
 1, 0.0,0.0,0.0,0,517)
DeclareVariable("demultiplex2_2.n4", "Dimension of output signal connector 4 [:#(type=Integer)]",\
 1, 0.0,0.0,0.0,0,517)
DeclareVariable("demultiplex2_2.n5", "Dimension of output signal connector 5 [:#(type=Integer)]",\
 1, 0.0,0.0,0.0,0,517)
DeclareAlias2("demultiplex2_2.u[1]", "Connector of Real input signals", "Vt", 1,\
 3, 0, 0)
DeclareAlias2("demultiplex2_2.u[2]", "Connector of Real input signals", "Q", 1, 3,\
 1, 0)
DeclareAlias2("demultiplex2_2.u[3]", "Connector of Real input signals", "P", 1, 3,\
 2, 0)
DeclareAlias2("demultiplex2_2.u[4]", "Connector of Real input signals", "w", 1, 3,\
 3, 0)
DeclareAlias2("demultiplex2_2.u[5]", "Connector of Real input signals", "delta", 1,\
 3, 4, 0)
DeclareAlias2("demultiplex2_2.y1[1]", "Connector of Real output signals 1", "Vt", 1,\
 3, 0, 0)
DeclareAlias2("demultiplex2_2.y2[1]", "Connector of Real output signals 2", "Q", 1,\
 3, 1, 0)
DeclareAlias2("demultiplex2_2.y3[1]", "Connector of Real output signals 3", "P", 1,\
 3, 2, 0)
DeclareAlias2("demultiplex2_2.y4[1]", "Connector of Real output signals 4", "w", 1,\
 3, 3, 0)
DeclareAlias2("demultiplex2_2.y5[1]", "Connector of Real output signals 5", \
"delta", 1, 3, 4, 0)
DeclareAlias2("addy[1].u1", "Connector of Real input signal 1", "stateSpace.y[1]", 1,\
 5, 135, 0)
DeclareVariable("addy[1].u2", "Connector of Real input signal 2", 1.0, 0.0,0.0,\
0.0,0,513)
DeclareAlias2("addy[1].y", "Connector of Real output signal", "Vt", 1, 3, 0, 0)
DeclareVariable("addy[1].k1", "Gain of input signal 1", 1, 0.0,0.0,0.0,0,513)
DeclareVariable("addy[1].k2", "Gain of input signal 2", 1, 0.0,0.0,0.0,0,513)
DeclareAlias2("addy[2].u1", "Connector of Real input signal 1", "stateSpace.y[2]", 1,\
 5, 136, 0)
DeclareVariable("addy[2].u2", "Connector of Real input signal 2", \
0.4360022246837616, 0.0,0.0,0.0,0,513)
DeclareAlias2("addy[2].y", "Connector of Real output signal", "Q", 1, 3, 1, 0)
DeclareVariable("addy[2].k1", "Gain of input signal 1", 1, 0.0,0.0,0.0,0,513)
DeclareVariable("addy[2].k2", "Gain of input signal 2", 1, 0.0,0.0,0.0,0,513)
DeclareAlias2("addy[3].u1", "Connector of Real input signal 1", "stateSpace.y[3]", 1,\
 5, 137, 0)
DeclareVariable("addy[3].u2", "Connector of Real input signal 2", \
0.8999999761581421, 0.0,0.0,0.0,0,513)
DeclareAlias2("addy[3].y", "Connector of Real output signal", "P", 1, 3, 2, 0)
DeclareVariable("addy[3].k1", "Gain of input signal 1", 1, 0.0,0.0,0.0,0,513)
DeclareVariable("addy[3].k2", "Gain of input signal 2", 1, 0.0,0.0,0.0,0,513)
DeclareAlias2("addy[4].u1", "Connector of Real input signal 1", "stateSpace.y[4]", 1,\
 5, 138, 0)
DeclareVariable("addy[4].u2", "Connector of Real input signal 2", 1.0, 0.0,0.0,\
0.0,0,513)
DeclareAlias2("addy[4].y", "Connector of Real output signal", "w", 1, 3, 3, 0)
DeclareVariable("addy[4].k1", "Gain of input signal 1", 1, 0.0,0.0,0.0,0,513)
DeclareVariable("addy[4].k2", "Gain of input signal 2", 1, 0.0,0.0,0.0,0,513)
DeclareAlias2("addy[5].u1", "Connector of Real input signal 1", "stateSpace.y[5]", 1,\
 5, 139, 0)
DeclareVariable("addy[5].u2", "Connector of Real input signal 2", \
1.2242474555969238, 0.0,0.0,0.0,0,513)
DeclareAlias2("addy[5].y", "Connector of Real output signal", "delta", 1, 3, 4, 0)
DeclareVariable("addy[5].k1", "Gain of input signal 1", 1, 0.0,0.0,0.0,0,513)
DeclareVariable("addy[5].k2", "Gain of input signal 2", 1, 0.0,0.0,0.0,0,513)
DeclareVariable("Pmchange.k", "Constant output value", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("Pmchange.y", "Connector of Real output signal", 0.0, 0.0,0.0,\
0.0,0,513)
DeclareVariable("multiplex5_1.n1", "Dimension of input signal connector 1 [:#(type=Integer)]",\
 1, 0.0,0.0,0.0,0,517)
DeclareVariable("multiplex5_1.n2", "Dimension of input signal connector 2 [:#(type=Integer)]",\
 1, 0.0,0.0,0.0,0,517)
DeclareVariable("multiplex5_1.n3", "Dimension of input signal connector 3 [:#(type=Integer)]",\
 1, 0.0,0.0,0.0,0,517)
DeclareVariable("multiplex5_1.n4", "Dimension of input signal connector 4 [:#(type=Integer)]",\
 1, 0.0,0.0,0.0,0,517)
DeclareVariable("multiplex5_1.n5", "Dimension of input signal connector 5 [:#(type=Integer)]",\
 1, 0.0,0.0,0.0,0,517)
DeclareVariable("multiplex5_1.u1[1]", "Connector of Real input signals 1", 1.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("multiplex5_1.u2[1]", "Connector of Real input signals 2", \
0.4360022246837616, 0.0,0.0,0.0,0,513)
DeclareVariable("multiplex5_1.u3[1]", "Connector of Real input signals 3", \
0.8999999761581421, 0.0,0.0,0.0,0,513)
DeclareVariable("multiplex5_1.u4[1]", "Connector of Real input signals 4", 1.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("multiplex5_1.u5[1]", "Connector of Real input signals 5", \
1.2242474555969238, 0.0,0.0,0.0,0,513)
DeclareVariable("multiplex5_1.y[1]", "Connector of Real output signals", 1.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("multiplex5_1.y[2]", "Connector of Real output signals", \
0.4360022246837616, 0.0,0.0,0.0,0,513)
DeclareVariable("multiplex5_1.y[3]", "Connector of Real output signals", \
0.8999999761581421, 0.0,0.0,0.0,0,513)
DeclareVariable("multiplex5_1.y[4]", "Connector of Real output signals", 1.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("multiplex5_1.y[5]", "Connector of Real output signals", \
1.2242474555969238, 0.0,0.0,0.0,0,513)
DeclareVariable("y0_Vt.k", "Constant output value", 1, 0.0,0.0,0.0,0,513)
DeclareVariable("y0_Vt.y", "Connector of Real output signal", 1.0, 0.0,0.0,0.0,0,513)
DeclareVariable("y0_Q.k", "Constant output value", 0.4360022246837616, 0.0,0.0,\
0.0,0,513)
DeclareVariable("y0_Q.y", "Connector of Real output signal", 0.4360022246837616,\
 0.0,0.0,0.0,0,513)
DeclareVariable("y0_P.k", "Constant output value", 0.8999999761581421, 0.0,0.0,\
0.0,0,513)
DeclareVariable("y0_P.y", "Connector of Real output signal", 0.8999999761581421,\
 0.0,0.0,0.0,0,513)
DeclareVariable("y0_w.k", "Constant output value", 1, 0.0,0.0,0.0,0,513)
DeclareVariable("y0_w.y", "Connector of Real output signal", 1.0, 0.0,0.0,0.0,0,513)
DeclareVariable("y0_delta.k", "Constant output value", 1.2242474555969238, \
0.0,0.0,0.0,0,513)
DeclareVariable("y0_delta.y", "Connector of Real output signal", \
1.2242474555969238, 0.0,0.0,0.0,0,513)
DeclareVariable("Ploadchange.k", "Constant output value", 0, 0.0,0.0,0.0,0,513)
DeclareVariable("Ploadchange.y", "Connector of Real output signal", 0.0, \
0.0,0.0,0.0,0,513)
DeclareOutput("CPUtime", "[s]", 5, 0.0, 0.0,0.0,0.0,0,512)
DeclareOutput("EventCounter", "", 6, 0.0, 0.0,0.0,0.0,0,512)
EndNonAlias(0)

#define DymolaHaveUpdateInitVars 1
#include <dsblock5.c>

DYMOLA_STATIC void UpdateInitVars(double*time, double* X_, double* XD_, double* U_, double* DP_, int IP_[], Dymola_bool LP_[], double* F_, double* Y_, double* W_, double QZ_[], double duser_[], int iuser_[], void*cuser_[],struct DYNInstanceData*did_,int initialCall) {
}
StartDataBlock
EndDataBlock
